name: Terraform Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  terraform_init:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./terraform 

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Zip Lambda Function
        run: |
          cd ../lambda/tsx_ticker_update/
          zip -r lambda_function.zip lambda.py 
          cd ../../terraform/
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
         
      - name: Terraform Format
        run: terraform fmt -check
         
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
        
      # Uncomment for automatic apply
      #- name: Terraform Apply
      #  run: terraform apply -auto-approve
